from typing import Any

config: dict[str, Any] = {
    "prabayar": {
        "dataset_path": "data/prabayar_450.csv",
        "model_path": "results/prabayar/models/model_prabayar.json",
        "metrics_dir": "results/prabayar/metrics",
        "layer_sizes": None, # set dynamically: [input, 64, 32, 1]
        "hidden_layers": [128, 64],
        "learning_rate": 0.001,
        "patience": 10,
        "min_delta": 1e-5,
        "clip_value": 1.0,
        "batch_size": 16,
        "l2_lambda": 1e-1,
        "lr_decay": 0.001,
        "target_label": "durasi token (hari)",
        "target": "Token_Habis_Dalam_Hari",
        "use_log_transform": False,
        "asymmetric_alpha": 0.6,
    },

    # Capacity-specific model configurations
    "capacity_configs": {
        "450": {
            "dataset_path": "data/prabayar_450.csv",
            "model_path": "results/prabayar_450/models/model_prabayar_450_tl.json",
            "metrics_dir": "results/prabayar_450/metrics_tl",
            "layer_sizes": None,
            "hidden_layers": [128, 64],  # Changed for transfer learning to match base model
            "learning_rate": 0.0001, # Smaller LR for fine-tuning
            "patience": 15,
            "min_delta": 1e-5,
            "clip_value": 5.0,
            "batch_size": 8,  # Smaller batch for small dataset
            "l2_lambda": 1e-2,  # Stronger regularization
            "lr_decay": 0.001,
            "target_label": "durasi token (hari)",
            "target": "Token_Habis_Dalam_Hari",
            "use_log_transform": False,
            "asymmetric_alpha": 0.6,
        },
        "900": {
            "dataset_path": "data/prabayar_900.csv",
            "model_path": "results/prabayar_900/models/model_prabayar_900_tl.json",
            "metrics_dir": "results/prabayar_900/metrics_tl",
            "layer_sizes": None,
            "hidden_layers": [128, 64],  # Full capacity model (259 samples - largest dataset)
            "learning_rate": 0.00001,
            "patience": 10,
            "min_delta": 1e-5,
            "clip_value": 5.0,
            "batch_size": 16,
            "l2_lambda": 1e-1,
            "lr_decay": 0.001,
            "target_label": "durasi token (hari)",
            "target": "Token_Habis_Dalam_Hari",
            "use_log_transform": False,
            "asymmetric_alpha": 0.6,
        },
        "1300": {
            "dataset_path": "data/prabayar_1300.csv",
            "model_path": "results/prabayar_1300/models/model_prabayar_1300_tl.json",
            "metrics_dir": "results/prabayar_1300/metrics_tl",
            "layer_sizes": None,
            "hidden_layers": [128, 64],  # Medium network (149 samples)
            "learning_rate": 0.0001,
            "patience": 10,
            "min_delta": 1e-5,
            "clip_value": 5.0,
            "batch_size": 16,
            "l2_lambda": 1e-1,
            "lr_decay": 0.001,
            "target_label": "durasi token (hari)",
            "target": "Token_Habis_Dalam_Hari",
            "use_log_transform": False,
            "asymmetric_alpha": 0.6,
        },
        "2200": {
            "dataset_path": "data/prabayar_2200.csv",
            "model_path": "results/prabayar_2200/models/model_prabayar_2200_tl.json",
            "metrics_dir": "results/prabayar_2200/metrics_tl",
            "layer_sizes": None,
            "hidden_layers": [128, 64],  # Medium network (141 samples)
            "learning_rate": 0.0001,
            "patience": 10,
            "min_delta": 1e-5,
            "clip_value": 5.0,
            "batch_size": 16,
            "l2_lambda": 1e-1,
            "lr_decay": 0.001,
            "target_label": "durasi token (hari)",
            "target": "Token_Habis_Dalam_Hari",
            "use_log_transform": False,
            "asymmetric_alpha": 0.6,
        },
        "3500": {
            "dataset_path": "data/prabayar_3500.csv",
            "model_path": "results/prabayar_3500/models/model_prabayar_3500_tl.json",
            "metrics_dir": "results/prabayar_3500/metrics_tl",
            "layer_sizes": None,
            "hidden_layers": [128, 64],  # Very simple network (only 11 samples!)
            "learning_rate": 0.0001,
            "patience": 20,
            "min_delta": 1e-5,
            "clip_value": 5.0,
            "batch_size": 4,  # Very small batch
            "l2_lambda": 5e-2,  # Very strong regularization
            "lr_decay": 0.001,
            "target_label": "durasi token (hari)",
            "target": "Token_Habis_Dalam_Hari",
            "use_log_transform": False,
            "asymmetric_alpha": 0.6,
        },
    },

    "features": {
        "prabayar": [
            "Jumlah_Anggota_Keluarga",
            "Daya_Listrik_Rumah_VA",
            "Nominal_Token_Terakhir_Rp",
            "Frekuensi_Isi_Token_Per_Bulan",
            "Kulkas_Jumlah",
            "Kulkas_Energi_kWhPerHari",
            "TV_Energi_kWhPerHari",
            "AC_EstimasiJamPerHari",
            "Kipas_EstimasiJamPerHari",
            "Kipas_Energi_kWhPerHari",
            "RiceCooker_Jumlah",
            "RiceCooker_Energi_kWhPerHari",
            "MesinCuci_EstimasiFrekuensiPerMinggu",
            "Alat_Lain_Ada",
            "Total_Energi_Utama_kWhPerHari",
            "Tarif_PLN_Eksak_Rp",
            "Estimasi_kWh_Didapat",
            "Durasi_Dari_Frekuensi",
            "Rasio_Token_vs_Energi",
            "Energi_Per_Nominal",
            "Rasio_Fisika_vs_Frekuensi",
            "Status_Subsidi_Listrik",
            "Kulkas_Kategori",
            "Kulkas_EstimasiWattPerUnit",
            "Kulkas_EstimasiJamPerHari",
            "TV_Jumlah",
            "TV_Kategori",
            "TV_EstimasiWattPerUnit",
            "TV_EstimasiJamPerHari",
            "AC_Jumlah",
            "AC_Kategori",
            "AC_EstimasiWattPerUnit",
            "AC_Energi_kWhPerHari",
            "Kipas_Jumlah",
            "Kipas_Kategori",
            "Kipas_EstimasiWattPerUnit",
            "RiceCooker_Kategori",
            "RiceCooker_EstimasiWattPerUnit",
            "RiceCooker_EstimasiJamPerHari",
            "MesinCuci_Jumlah",
            "MesinCuci_Kategori",
            "MesinCuci_EstimasiWattPerUnit",
            "MesinCuci_EstimasiDurasiSekaliPakaiJam",
            "MesinCuci_Energi_kWhPerHari",
            "Alat_Lain_1_Jenis",
            "Alat_Lain_1_Jumlah",
            "Alat_Lain_1_Kategori",
            "Alat_Lain_1_EstimasiWatt",
            "Alat_Lain_1_EstimasiJamPerHari",
            "Alat_Lain_1_Energi_kWhPerHari",
            "Alat_Lain_2_Jenis",
            "Alat_Lain_2_Jumlah",
            "Alat_Lain_2_Kategori",
            "Alat_Lain_2_EstimasiWatt",
            "Alat_Lain_2_EstimasiJamPerHari",
            "Alat_Lain_2_Energi_kWhPerHari",
            "Alat_Lain_3_Jenis",
            "Alat_Lain_3_Jumlah",
            "Alat_Lain_3_Kategori",
            "Alat_Lain_3_EstimasiWatt",
            "Alat_Lain_3_EstimasiJamPerHari",
            "Alat_Lain_3_Energi_kWhPerHari",
            "Total_Energi_Alat_Lain_kWhPerHari",
            "Total_Energi_Semua_kWhPerHari",
            "Total_Energi_Semua_kWhPerBulan",
            "Estimasi_Tarif_Per_kWh_Rp",
            "Estimasi_Biaya_Energi_Bulanan_Rp",
            "Estimasi_Fisika_Durasi_Hari",
            "Token_Nominal_Kategori",
            "Fisika_vs_Frekuensi_Gap",
            "Daya_x_TotalEnergi",
            "AC_PK_Kategori",
        ],
    },

    "numeric_cols": [
        "Jumlah_Anggota_Keluarga",
        "Daya_Listrik_Rumah_VA",

        "Kulkas_Jumlah",
        "Kulkas_EstimasiWattPerUnit",
        "Kulkas_EstimasiJamPerHari",
        "Kulkas_Energi_kWhPerHari",

        "TV_Jumlah",
        "TV_EstimasiWattPerUnit",
        "TV_EstimasiJamPerHari",
        "TV_Energi_kWhPerHari",

        "AC_Jumlah",
        "AC_EstimasiWattPerUnit",
        "AC_EstimasiJamPerHari",
        "AC_Energi_kWhPerHari",

        "Kipas_Jumlah",
        "Kipas_EstimasiWattPerUnit",
        "Kipas_EstimasiJamPerHari",
        "Kipas_Energi_kWhPerHari",

        "RiceCooker_Jumlah",
        "RiceCooker_EstimasiWattPerUnit",
        "RiceCooker_EstimasiJamPerHari",
        "RiceCooker_Energi_kWhPerHari",

        "MesinCuci_Jumlah",
        "MesinCuci_EstimasiWattPerUnit",
        "MesinCuci_EstimasiFrekuensiPerMinggu",
        "MesinCuci_EstimasiDurasiSekaliPakaiJam",
        "MesinCuci_Energi_kWhPerHari",

        "Total_Energi_Utama_kWhPerHari",
        "Total_Energi_Semua_kWhPerHari",

        "Nominal_Token_Terakhir_Rp",
        "Total_Energi_Semua_kWhPerBulan",
        "Estimasi_Tarif_Per_kWh_Rp",
        "Estimasi_Biaya_Energi_Bulanan_Rp",
        "Daya_x_TotalEnergi",
        "Tarif_PLN_Eksak_Rp",
        "Estimasi_kWh_Didapat",
        "Estimasi_Fisika_Durasi_Hari",
        "Durasi_Dari_Frekuensi",
        "Rasio_Token_vs_Energi",
        "Token_Nominal_Kategori",
        "Energi_Per_Nominal",
        "Fisika_vs_Frekuensi_Gap",
        "Rasio_Fisika_vs_Frekuensi",
    ],

    "ordinal_encoding": {
        "Kulkas_Kategori": {
            "Tidak ada": 0,
            "Tidak tahu": 0,
            "Kecil / 1 pintu": 1,
            "Sedang / 2 pintu": 2,
            "Besar / side by side": 3,
        },
        "TV_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, kurang dari 2 jam per hari": 1,
            "Sedang, sekitar 2-5 jam per hari": 2,
            "Sering, sekitar 6-10 jam per hari": 3,
            "Sangat sering, lebih dari 10 jam per hari": 4,
        },
        "AC_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, kurang dari 2 jam per hari": 1,
            "Sedang, sekitar 2-5 jam per hari": 2,
            "Sering, sekitar 6-10 jam per hari": 3,
            "Sangat sering, lebih dari 10 jam per hari": 4,
        },
        "Kipas_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, kurang dari 2 jam per hari": 1,
            "Sedang, sekitar 2-5 jam per hari": 2,
            "Sering, sekitar 6-10 jam per hari": 3,
            "Sangat sering, lebih dari 10 jam per hari": 4,
        },
        "RiceCooker_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, kurang dari 2 jam per hari": 1,
            "Sedang, sekitar 2-5 jam per hari": 2,
            "Sering, sekitar 6-10 jam per hari": 3,
            "Sangat sering, lebih dari 10 jam per hari": 4,
        },
        "MesinCuci_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, 1-2 kali per minggu": 1,
            "Sedang, 3-4 kali per minggu": 2,
            "Sering, 5-6 kali per minggu": 3,
            "Sangat sering, hampir setiap hari": 4,
        },
        "Alat_Lain_Ada": {
            "Tidak": 0,
            "Ya": 1,
        },
        "Alat_Lain_1_Kategori": {
            "Tidak diisi": 0,
            "Jarang, 1-2 kali per minggu": 1,
            "Sedang, 3-4 kali per minggu": 2,
            "Sering, hampir setiap hari": 3,
            "Sangat sering, setiap hari dan cukup lama": 4,
        },
        "Alat_Lain_2_Kategori": {
            "Tidak diisi": 0,
            "Jarang, 1-2 kali per minggu": 1,
            "Sedang, 3-4 kali per minggu": 2,
            "Sering, hampir setiap hari": 3,
            "Sangat sering, setiap hari dan cukup lama": 4,
        },
        "Alat_Lain_3_Kategori": {
            "Tidak diisi": 0,
            "Jarang, 1-2 kali per minggu": 1,
            "Sedang, 3-4 kali per minggu": 2,
            "Sering, hampir setiap hari": 3,
            "Sangat sering, setiap hari dan cukup lama": 4,
        },
    },

    "numeric_special": {
        "Daya_Listrik_Rumah_VA": {
            "Tidak tahu": 900,
            "> 5500": 7700,
        },
    },

    "one_hot_nominal": {
        "Alat_Lain_1_Jenis": [
            "Charger HP/perangkat kecil",
            "Blender/Mixer",
            "Setrika",
            "Dispenser",
            "Komputer/Laptop",
            "Pompa air",
            "Oven/Microwave",
            "Lainnya",
        ],
        "Alat_Lain_2_Jenis": [
            "Charger HP/perangkat kecil",
            "Blender/Mixer",
            "Setrika",
            "Dispenser",
            "Komputer/Laptop",
            "Pompa air",
            "Oven/Microwave",
            "Lainnya",
        ],
        "Alat_Lain_3_Jenis": [
            "Charger HP/perangkat kecil",
            "Blender/Mixer",
            "Setrika",
            "Dispenser",
            "Komputer/Laptop",
            "Pompa air",
            "Oven/Microwave",
            "Lainnya",
        ],
    },
    "tidak_tahu_cols": [
        "Kulkas_Kategori",
    ],
    "tidak_diisi_cols": [
        "Alat_Lain_1_Kategori",
        "Alat_Lain_2_Kategori",
        "Alat_Lain_3_Kategori",
    ],
    "one_hot_cols": [
        "Alat_Lain_1_Jenis",
        "Alat_Lain_2_Jenis",
        "Alat_Lain_3_Jenis"
    ],

    # Kolom yang menggunakan probability encoding
    # Nilai biner (0/1) diganti dengan probabilitas kemunculan kategori dari data training
    "probability_encoding_cols": {
        # Kolom binary mapping: nilai 1 diganti P(kategori aktif)
        "binary": [
            "Status_Subsidi_Listrik",
            "Alat_Lain_Ada",
        ],
        # Kolom one-hot: nilai 1 di tiap kolom OHE diganti P(kategori tersebut)
        "one_hot": [
            "Alat_Lain_1_Jenis",
            "Alat_Lain_2_Jenis",
            "Alat_Lain_3_Jenis",
        ],
    },
    "ohe_fixed_categories": {
        "Alat_Lain_1_Jenis": [
            "Charger HP/perangkat kecil",
            "Blender/Mixer",
            "Setrika",
            "Dispenser",
            "Komputer/Laptop",
            "Pompa air",
            "Oven/Microwave",
            "Lainnya",
        ],
        "Alat_Lain_2_Jenis": [
            "Charger HP/perangkat kecil",
            "Blender/Mixer",
            "Setrika",
            "Dispenser",
            "Komputer/Laptop",
            "Pompa air",
            "Oven/Microwave",
            "Lainnya",
        ],
        "Alat_Lain_3_Jenis": [
            "Charger HP/perangkat kecil",
            "Blender/Mixer",
            "Setrika",
            "Dispenser",
            "Komputer/Laptop",
            "Pompa air",
            "Oven/Microwave",
            "Lainnya",
        ],
    },
    "ordinal_maps": {
        "Kulkas_Kategori": {
            "Tidak ada": 0,
            "Kecil / 1 pintu": 1,
            "Sedang / 2 pintu": 2,
            "Besar / side by side": 3,
        },
        "TV_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, kurang dari 2 jam per hari": 1,
            "Sedang, sekitar 2-5 jam per hari": 2,
            "Sering, sekitar 6-10 jam per hari": 3,
            "Sangat sering, lebih dari 10 jam per hari": 4,
        },
        "AC_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, kurang dari 2 jam per hari": 1,
            "Sedang, sekitar 2-5 jam per hari": 2,
            "Sering, sekitar 6-10 jam per hari": 3,
            "Sangat sering, lebih dari 10 jam per hari": 4,
        },
        "AC_PK_Kategori": {
            "Tidak ada AC": 0,
            "Tidak tahu": 0,
            "1/2 PK": 1,
            "3/4 PK": 2,
            "1 PK": 3,
            "1.5 PK": 4,
        },
        "Kipas_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, kurang dari 2 jam per hari": 1,
            "Sedang, sekitar 2-5 jam per hari": 2,
            "Sering, sekitar 6-10 jam per hari": 3,
            "Sangat sering, lebih dari 10 jam per hari": 4,
        },
        "RiceCooker_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, kurang dari 2 jam per hari": 1,
            "Sedang, sekitar 2-5 jam per hari": 2,
            "Sering, sekitar 6-10 jam per hari": 3,
            "Sangat sering, lebih dari 10 jam per hari": 4,
        },
        "MesinCuci_Kategori": {
            "Tidak ada / tidak digunakan": 0,
            "Jarang, 1-2 kali per minggu": 1,
            "Sedang, 3-4 kali per minggu": 2,
            "Sering, 5-6 kali per minggu": 3,
            "Sangat sering, hampir setiap hari": 4,
        },
        "Alat_Lain_1_Kategori": {
            "Jarang, 1-2 kali per minggu": 0,
            "Sedang, 3-4 kali per minggu": 1,
            "Sering, hampir setiap hari": 2,
            "Sangat sering, setiap hari dan cukup lama": 3,
        },
        "Alat_Lain_2_Kategori": {
            "Jarang, 1-2 kali per minggu": 0,
            "Sedang, 3-4 kali per minggu": 1,
            "Sering, hampir setiap hari": 2,
            "Sangat sering, setiap hari dan cukup lama": 3,
        },
        "Alat_Lain_3_Kategori": {
            "Jarang, 1-2 kali per minggu": 0,
            "Sedang, 3-4 kali per minggu": 1,
            "Sering, hampir setiap hari": 2,
            "Sangat sering, setiap hari dan cukup lama": 3,
        },
        "Alat_Lain_1_Jenis": {
            "Tidak diisi": 0,
            "Charger HP/perangkat kecil": 1,
            "Blender/Mixer": 2,
            "Setrika": 3,
            "Dispenser": 4,
            "Komputer/Laptop": 5,
            "Pompa air": 6,
            "Oven/Microwave": 7,
            "Lainnya": 8,
        },
        "Alat_Lain_2_Jenis": {
            "Tidak diisi": 0,
            "Charger HP/perangkat kecil": 1,
            "Blender/Mixer": 2,
            "Setrika": 3,
            "Dispenser": 4,
            "Komputer/Laptop": 5,
            "Pompa air": 6,
            "Oven/Microwave": 7,
            "Lainnya": 8,
        },
        "Alat_Lain_3_Jenis": {
            "Tidak diisi": 0,
            "Charger HP/perangkat kecil": 1,
            "Blender/Mixer": 2,
            "Setrika": 3,
            "Dispenser": 4,
            "Komputer/Laptop": 5,
            "Pompa air": 6,
            "Oven/Microwave": 7,
            "Lainnya": 8,
        },
    },
}
